import type { PromptAsset } from "./prompt-types";

const promptAssets: Readonly<Record<string, PromptAsset>> = {
  "project-profile-recognition.md": {
    file: "project-profile-recognition.md",
    task: "新建项目基础档案识别",
    route: "app/api/projects/profile-recognition/route.ts",
    model: "strong",
    risk: "高",
    output: "项目名称、简介、领域、应用场景、关键词、产品形态",
    status: "已接入",
  },
  "project-trl-evidence-recognition.md": {
    file: "project-trl-evidence-recognition.md",
    task: "TRL 证据提取",
    route: "app/api/projects/profile-recognition/route.ts",
    model: "strong",
    risk: "高",
    output: "交付物类型、证据矩阵、缺失证据、置信度",
    status: "已接入",
  },
  "training-qa-question-generation.md": {
    file: "training-qa-question-generation.md",
    task: "训练流程评委问题生成",
    route: "app/training/[sessionId]/qa/questions/generate/route.ts",
    model: "strong",
    risk: "高",
    output: "Q1/Q2/Q3 评委问题",
    status: "已接入",
  },
  "dynamic-followup.md": {
    file: "dynamic-followup.md",
    task: "动态追问主 Prompt",
    route: "app/training/[sessionId]/qa/questions/dynamic-followup/route.ts",
    model: "strong",
    risk: "高",
    output: "一个追问或 NO_DYNAMIC_FOLLOWUP",
    status: "已接入",
  },
  "dynamic-followup-mismatch.md": {
    file: "dynamic-followup-mismatch.md",
    task: "动态追问兜底：上下文不匹配",
    route: "app/training/[sessionId]/qa/questions/dynamic-followup/route.ts",
    model: "strong",
    risk: "中",
    output: "一个追问或 NO_DYNAMIC_FOLLOWUP",
    status: "已接入",
  },
  "dynamic-followup-content.md": {
    file: "dynamic-followup-content.md",
    task: "动态追问兜底：内容充足",
    route: "app/training/[sessionId]/qa/questions/dynamic-followup/route.ts",
    model: "strong",
    risk: "中",
    output: "一个追问",
    status: "已接入",
  },
  "pitch-performance-analysis.md": {
    file: "pitch-performance-analysis.md",
    task: "训练报告 / 路演表现分析",
    route: "app/training/[sessionId]/analysis/route.ts",
    model: "strong",
    risk: "高",
    output: "评分、结论、优势、短板、改进建议",
    status: "已接入",
  },
  "question-generation.md": {
    file: "question-generation.md",
    task: "项目详情页模拟评委问题",
    route: "app/projects/[id]/questions/generate/route.ts",
    model: "strong",
    risk: "中",
    output: "模拟评委问题",
    status: "已接入",
  },
  "material-diagnosis.md": {
    file: "material-diagnosis.md",
    task: "材料诊断",
    route: "app/projects/[id]/diagnosis/route.ts",
    model: "strong",
    risk: "中",
    output: "材料问题、优化建议",
    status: "已接入",
  },
  "scoring.md": {
    file: "scoring.md",
    task: "评分辅助",
    route: "app/projects/[id]/scoring/route.ts",
    model: "strong",
    risk: "中",
    output: "评分维度或评分建议",
    status: "已接入",
  },
  "project-summary.md": {
    file: "project-summary.md",
    task: "AI 连通性测试 / 轻量摘要",
    route: "app/api/ai/test/route.ts",
    model: "fast",
    risk: "低",
    output: "轻量摘要或测试返回",
    status: "已接入",
  },
  "answer-feedback.md": {
    file: "answer-feedback.md",
    task: "答案反馈",
    route: "当前未发现调用",
    model: "待确认",
    risk: "低",
    output: "历史模板，后续确认是否清理",
    status: "未接入",
  },
  "final-report.md": {
    file: "final-report.md",
    task: "旧报告模板",
    route: "当前未发现调用",
    model: "待确认",
    risk: "低",
    output: "历史模板，后续确认是否清理",
    status: "未接入",
  },
};

export function getPromptAsset(file: string): PromptAsset {
  return (
    promptAssets[file] ?? {
      file,
      task: "未登记",
      route: "未登记",
      model: "待确认",
      risk: "待确认",
      output: "未登记",
      status: "未接入",
    }
  );
}
